In [2]:
import pandas as pd
import seaborn as sns 
import numpy as np 
from matplotlib import pyplot as plt
import os
import glob

In [3]:
df = pd.read_csv('Data_Sources/JB_Glassdoor__1_col_.csv')

In [4]:
df

                                              Column 1
0                                    Reservations Crew
1                           Analyst Strategic Planning
2                Analyst Financial Planning & Analysis
3                   Executive Assistant Administrative
4                                               Intern
5                 Associate Analyst Revenue Management
6                           Director Loyalty Marketing
7          Analyst Financial (JetBlue Travel Products)
8     Manager Data Analytics (JetBlue Travel Products)
9                                     Generalist Field
10                       Manager IT Corporate Products
11                           Ground Operations Crew PT
12                                  Manager Facilities
13   Manager Internal Content, Corporate Communicat...
14                                    Analyst Treasury
15                    Senior Analyst Corporate Finance
16               Project Manager IT Cust Supp Products
17           Coordinator Onboard Experience Compliance
18                                Manager Brand Design
19                      Analyst IT Operations Products
20                                   JET Intern People
21                                       JET Intern IT
22                 Airport Operations Crew Seasonal PT
23                          Analyst Revenue Management
24                                 Developer Front End
25                          Developer Application Lead
26                                   JET Intern, Legal
27                         IT Analyst Customer Support
28              Senior Analyst Strategy & Business Dev
29                              Technician Maintenance
..                                                 ...
75                           Auditor Quality Assurance
76                        Technical Support Controller
77                       Associate Developer Front End
78               Director Labor and Employment Counsel
79                      Engineer IT Systems Monitoring
80                  Senior Analyst Operations Strategy
81                       Senior Analyst Route Planning
82                                      AOG Controller
83                   Director Enterprise QA Compliance
84                              Controller Maintenance
85                             JET Intern Tax (Income)
86                  Senior Analyst Financial Reporting
87                          Senior Analyst ASAP & FRMS
88                       Associate Engineer Industrial
89                        Engineer Service Fulfillment
90                 Senior Analyst Content & Technology
91                 Engineer Analytics and Optimization
92                        Senior Architect IT Security
93            General Manager IT Security & Infra Arch
94                                 Engineer Structures
95                  Senior Architect IT Infrastructure
96                  Director Fleet Strategy & Programs
97                      Analyst IT Security Operations
98                               Architect IT Security
99                           Engineer Aircraft Systems
100           Supervisor Airport and Ground Operations
101           Supervisor Airport and Ground Operations
102                              Inflight Crew Trainee
103           Supervisor Airport and Ground Operations
104                         Airport Operations Crew PT

[105 rows x 1 columns]

In [11]:
#categorize the job vacancies on whether they are digital/tech or management using keyworks

searchfor_tech = [' IT ', ' IT', '-IT', 'IT-', 'Digital', 'Technology', 'Automation', 'Developer', ' API ',
                  'Data', 'Agile', '-Entwicklung', ' Entwicklung', '-Entwickler', 'Entwickler', 'Informatik', 
                  'eLearning', 'online', 'Software', 'DevOps', 'Information Management', 'Innovation', 
                  'Product Owner', 'Product Manager', ' Mobile ', 'Architect', ' UX ', 'UX/', ' UX', 'Cisco',' SAP ',
                  'SAP-', 'Scrum', 'Business Intelligence', 'DÃ©veloppement Informatique', 'Transformation',
                  ' Internet ', 'Web ', ' Architecte ', 'E-commerce', 'Tech Ops', ' API', 'API ', 'Hacking',
                  'Analytics', 'IT Analyst']

searchfor_mang = ['Manager', 'Managing Director', 'Head of', 'Leader', 'Director']

df['Technology'] = np.where(df['Column 1'].str.contains('|'.join(searchfor_tech), case=False, na=False), '1', '0')

df['Management'] = np.where(df['Column 1'].str.contains('|'.join(searchfor_mang), case=False, na=False), '1', '0')

In [12]:
# share of vacancies that are management 

df.Management.value_counts(normalize=True, sort=True, bins=None, dropna=True)

0    0.780952
1    0.219048
Name: Management, dtype: float64

In [13]:
# share of vacancies that are technology

df.Technology.value_counts(normalize=True, sort=True, bins=None, dropna=True)

0    0.704762
1    0.295238
Name: Technology, dtype: float64

In [14]:
df.sample(n=50)

                                          Column 1 Technology Management
49                               Auditor Corporate          0          0
36                         Analyst CASS Compliance          0          0
34                  Developer Application Services          1          0
32            Analyst IT Customer Support Products          1          0
86              Senior Analyst Financial Reporting          0          0
72                     Manager IT PCI & Compliance          1          1
42          Project Manager IT Operations Products          1          1
77                   Associate Developer Front End          1          0
58              JET Summer Intern Customer Support          0          0
37              Ground Operations Crew Seasonal PT          0          0
17       Coordinator Onboard Experience Compliance          0          0
69                             Industrial Engineer          0          0
25                      Developer Application Lead          1          0
85                         JET Intern Tax (Income)          0          0
89                    Engineer Service Fulfillment          0          0
97                  Analyst IT Security Operations          1          0
54                          Supervisor Maintenance          0          0
5             Associate Analyst Revenue Management          0          0
27                     IT Analyst Customer Support          1          0
45               Director Corporate Communications          0          1
3               Executive Assistant Administrative          0          0
20                               JET Intern People          0          0
2            Analyst Financial Planning & Analysis          0          0
23                      Analyst Revenue Management          0          0
35                     Analyst IT Application ITSM          1          0
83               Director Enterprise QA Compliance          0          1
81                   Senior Analyst Route Planning          0          0
55                        Engineer Product Release          0          0
24                             Developer Front End          1          0
30                     Supervisor ITSM Application          1          0
38   Product Engineer UX (JetBlue Travel Products)          1          0
101       Supervisor Airport and Ground Operations          0          0
87                      Senior Analyst ASAP & FRMS          0          0
76                    Technical Support Controller          0          0
75                       Auditor Quality Assurance          0          0
4                                           Intern          0          0
47                                   Manager Fleet          0          1
63                             Engineer IT Systems          1          0
0                                Reservations Crew          0          0
50                              Manager Properties          0          1
92                    Senior Architect IT Security          1          0
102                          Inflight Crew Trainee          0          0
88                   Associate Engineer Industrial          0          0
62         Business Analyst IT Digital & Cust Prod          1          0
39                 Senior Analyst Manpower Systems          0          0
19                  Analyst IT Operations Products          1          0
14                                Analyst Treasury          0          0
74               Senior Analyst Strategic Sourcing          0          0
103       Supervisor Airport and Ground Operations          0          0
82                                  AOG Controller          0          0

In [15]:
# create a new column Tech_Mang which indicates jobs that are BOTH technolgy and management 

def tech(df):
    if df['Management'] == '1' and df['Technology'] == '1':
        return '1'
    else:
        return '0'
    
df['Tech_Mang'] = df.apply(tech, axis=1)
df

,Column 1,Technology,Management,Tech_Mang
0,Reservations Crew,0,0,0
1,Analyst Strategic Planning,0,0,0
2,Analyst Financial Planning & Analysis,0,0,0
3,Executive Assistant Administrative,0,0,0
4,Intern,0,0,0
5,Associate Analyst Revenue Management,0,0,0
6,Director Loyalty Marketing,0,1,0
7,Analyst Financial (JetBlue Travel Products),0,0,0
8,Manager Data Analytics (JetBlue Travel Products),1,1,1
9,Generalist Field,0,0,0
10,Manager IT Corporate Products,1,1,1
11,Ground Operations Crew PT,0,0,0
12,Manager Facilities,0,1,0
13,"Manager Internal Content, Corporate Communicat...",0,1,0
14,Analyst Treasury,0,0,0
15,Senior Analyst Corporate Finance,0,0,0
16,Project Manager IT Cust Supp Products,1,1,1
17,Coordinator Onboard Experience Compliance,0,0,0
18,Manager Brand Design,0,1,0
19,Analyst IT Operations Products,1,0,0
20,JET Intern People,0,0,0
21,JET Intern IT,1,0,0
22,Airport Operations Crew Seasonal PT,0,0,0
23,Analyst Revenue Management,0,0,0
24,Developer Front End,1,0,0
25,Developer Application Lead,1,0,0
26,"JET Intern, Legal",0,0,0
27,IT Analyst Customer Support,1,0,0
28,Senior Analyst Strategy & Business Dev,0,0,0
29,Technician Maintenance,0,0,0
...,...,...,...,...
75,Auditor Quality Assurance,0,0,0
76,Technical Support Controller,0,0,0
77,Associate Developer Front End,1,0,0
78,Director Labor and Employment Counsel,0,1,0
79,Engineer IT Systems Monitoring,1,0,0
80,Senior Analyst Operations Strategy,0,0,0
81,Senior Analyst Route Planning,0,0,0
82,AOG Controller,0,0,0
83,Director Enterprise QA Compliance,0,1,0
84,Controller Maintenance,0,0,0
85,JET Intern Tax (Income),0,0,0
86,Senior Analyst Financial Reporting,0,0,0
87,Senior Analyst ASAP & FRMS,0,0,0
88,Associate Engineer Industrial,0,0,0
89,Engineer Service Fulfillment,0,0,0
90,Senior Analyst Content & Technology,1,0,0
91,Engineer Analytics and Optimization,1,0,0
92,Senior Architect IT Security,1,0,0
93,General Manager IT Security & Infra Arch,1,1,1
94,Engineer Structures,0,0,0
95,Senior Architect IT Infrastructure,1,0,0
96,Director Fleet Strategy & Programs,0,1,0
97,Analyst IT Security Operations,1,0,0
98,Architect IT Security,1,0,0
99,Engineer Aircraft Systems,0,0,0
100,Supervisor Airport and Ground Operations,0,0,0
101,Supervisor Airport and Ground Operations,0,0,0
102,Inflight Crew Trainee,0,0,0
103,Supervisor Airport and Ground Operations,0,0,0
104,Airport Operations Crew PT,0,0,0

In [16]:
# share of vacancies that are both technology and management

y = df.Tech_Mang.value_counts(normalize=False, sort=True, bins=None, dropna=True)
x = df.Management.value_counts(normalize=False, sort=True, bins=None, dropna=True)

Tech_M = y[1]/x[1]
print(Tech_M)

0.34782608695652173

# saving the categorized vacancies to Excel

df.to_csv('Output/JB_Vacancies_Categorised.csv')
df.to_excel('Output/JB_Vacancies_Categorised.xlsx', sheet_name='Data')